name: CS fixer

on:
  pull_request:

permissions:
  contents: read

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  verify:
    name: Fabbot
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"

          pip install codespell &
          composer global require -q friendsofphp/php-cs-fixer &

          mkdir a

          gh api -H "Accept: application/vnd.github.v3.raw" \
              "/repos/$REPO_OWNER/$REPO_NAME/contents/.php-cs-fixer.dist.php?ref=$PR_HEAD_SHA" \
              > a/.php-cs-fixer.dist.php || rm a/.php-cs-fixer.dist.php &

          gh api --paginate "/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER/files" \
            | jq -c '.[] | select(.status != "removed") | {filename, sha}' \
            | while read -r FILE_OBJ; do
              FILENAME=$(echo "$FILE_OBJ" | jq -r '.filename')
              FILE_SHA=$(echo "$FILE_OBJ" | jq -r '.sha')

              mkdir -p "a/$(dirname "$FILENAME")"
              gh api -H "Accept: application/vnd.github.raw" \
                "/repos/$REPO_OWNER/$REPO_NAME/git/blobs/$FILE_SHA" \
                > "a/$FILENAME" &
            done

          wait

      - name: Check code style
        if: always()
        run: |
          cp -a a b && cd b
          ~/.composer/vendor/bin/php-cs-fixer fix --using-cache no --show-progress none
          cd ..

          if diff -q -r --no-dereference a/ b/ >/dev/null; then
            echo "::notice::PHP-CS-Fixer found no style issues. Code is clean! 🎉"
          else
            echo "::error::PHP-CS-Fixer found style issues. Please apply the patch below."
            echo -e "\n \ngit apply - <<'EOF_PATCH'"
            diff -u -p -r --no-dereference --color=always a/ b/ || true
            echo -e "EOF_PATCH\n \n"
            echo "Then commit the changes and push to your PR branch."
            exit 1
          fi

      - name: Check for common typos
        if: always()
        run: |
          rm -rf b && cp -a a b && cd b
          codespell -L invokable --check-filenames -w || true
          cd ..

          if diff -q -r --no-dereference a/ b/ >/dev/null; then
            echo "::notice::codespell found no typos issues. Code is clean! 🎉"
          else
            echo "::error::PHP-CS-Fixer found typos. Please apply the patch below."
            echo -e "\n \ngit apply - <<'EOF_PATCH'"
            diff -u -p -r --no-dereference --color=always a/ b/ || true
            echo -e "EOF_PATCH\n \n"
            echo "Then commit the changes and push to your PR branch."
            exit 1
          fi

      - name: Check for merge commits
        if: always()
        run: |
          gh api -H "Accept: application/vnd.github.v3+json" \
            "/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls/${{ github.event.pull_request.number }}/commits" \
            | jq -r '.[].parents | length > 1' | grep true && {
              echo "::error::Merge commits are not allowed in pull requests. Please rebase your branch."
              exit 1
            } || {
              echo "::notice::No merge commits found. Good job! 🎉"
            }

      - name: Check test-case methods
        if: always()
        run: |
          rm -rf b && cp -a a b && cd b
          find -wholename '**/Tests/**.php' \
            | while read -r FILE; do
              sed -i -E 's/^(    public function test.*): void$/\1/' "$FILE"
            done
          cd ..

          if diff -q -r --no-dereference a/ b/ >/dev/null; then
            echo "::notice::Test case methods are correctly formatted. Good job! 🎉"
          else
            echo "::error::Test case methods should not have a return type. Please apply the patch below."
            echo -e "\n \ngit apply - <<'EOF_PATCH'"
            diff -u -p -r --no-dereference --color=always a/ b/ || true
            echo -e "EOF_PATCH\n \n"
            echo "Then commit the changes and push to your PR branch."
            exit 1
          fi


      - name: Check @deprecated annotations
        if: always()
        run: |
          rm -rf b && cp -a a b && cd b
          find -name '*.php' \
            | while read -r FILE; do
              sed -i -E 's/(@deprecated since )([0-9])/\1Symfony \2/' "$FILE"
            done
          cd ..

          if diff -q -r --no-dereference a/ b/ >/dev/null; then
            echo "::notice::@deprecated annotations are correctly formatted. Good job! 🎉"
          else
            echo "::error::@deprecated annotations should mention Symfony. Please apply the patch below."
            echo -e "\n \ngit apply - <<'EOF_PATCH'"
            diff -u -p -r --no-dereference --color=always a/ b/ || true
            echo -e "EOF_PATCH\n \n"
            echo "Then commit the changes and push to your PR branch."
            exit 1
          fi

      - name: Check PR header
        if: always()
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"

          if [[ ! "$PR_BODY" =~ \|\ License[\ ]+\|\ MIT ]]; then
            echo "::error::You must add the standard Symfony PR contribution header in the description (see https://symfony.com/doc/current/contributing/code/patches.html#make-a-pull-request)."
            exit 1
          fi

          if [[ "$PR_TITLE" =~ (feat|fix|docs|style|refactor|perf|test|chore|revert|build|ci|types?|wip): ]]; then
            echo "::error::Don't use conventional prefixes in PR title. We'll add one while merging."
            exit 1
          fi
